### ISSUE TITLE
동명이인 구분 불가 (Unable to distinguish same names)

### ISSUE THREAD

**Issue by Hyun3246** [Hyun3246/KBO-Stats-Analysis#2]
동명이인 구분 불가 오류를 파악하였고 수정 예정입니다.

Checked Error 'Unable to distinguish same names'. About to solve.

**Comment by julnk0207** [comment]
이름 뒤에 알파벳을 추가하여 동명이인을 구별하였습니다.
명단에 선수를 추가하려면 알파벳까지 입력하여야 합니다.

Differentiated same name by adding an alphabet at the end of a name.
User should type name including an alphabet to add a player to the team.
